[package]
name = "indexify"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[workspace]
members = [".", "migration"]

[dependencies]
anyerror = { version = "0.1.10" }
anyhow = { version = "^1" }
async-trait = "0.1.74"
axum = { version = "^0", features = ["multipart"] }
axum-macros = { version = "0.3.7" }
axum-otel-metrics = "0.6"
axum-tracing-opentelemetry = "0.14.1"
byteorder = "1.5.0"
bytes = "1.5.0"
clap = { version = "^4", features = ["derive"] }
figment = { version = "0.10.8", features = ["yaml", "env"] }
hostname = { version = "^0" }
itertools = "0.11.0"
nanoid = { version = "0.4.0" }
openraft = { version = "0.8.3", features = ["serde", "anyhow"] }
opensearch = { version = "2.1.0" }
opentelemetry = { version = "^0", features = ["rt-async-std"] }
opentelemetry_sdk = "0.20.0"
opentelemetry-semantic-conventions = "0.12.0"
opentelemetry-otlp = { version = "*", features = [
    "http-proto",
    "reqwest-client",
] }
opentelemetry-stdout = {version = "0.1.0", features = ["logs", "metrics", "trace"]}
names = {version = "0.14.0", default-features = false }
pyo3 = { version = "^0", features = ["auto-initialize"] }
pythonize = "0.20.0"
qdrant-client = "1.2.0"
rand = { version = "^0" }
regex = { version = "^1" }
reqwest = { version = "^0", features = ["json"] }
sea-orm = { version = "^0", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "sqlx-dep",
    "debug-print",
    "with-json",
    "with-time",
    "postgres-array",
] }
sea-query = { version = "^0", features = ["postgres-array"] }
serde = { version = "^1", features = ["derive"] }
serde_yaml = { version = "^0" }
serde_json = { version = "^1", features = ["std"] }
smart-default = { version = "^0" }
strum = { version = "^0", features = ["derive"] }
strum_macros = { version = "^0" }
tempfile = "3.8.0"
thiserror = "*"
tokio = { version = "^1", features = ["full"] }
tracing = { version = "^0", features = ["log"] }
tracing-core = "0.1.31"
tracing-opentelemetry = { version = "0.21" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "*"
utoipa = { version = "^4", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "^4", features = ["axum"] }
utoipa-rapidoc = { version = "^1", features = ["axum"] }
utoipa-redoc = { version = "^1", features = ["axum"] }
object_store = "0.7.0"
local-ip-address = {version = "0.5.6"}

[dev-dependencies]
migration = { path = "./migration" }
tracing-test = { version = "^0", features = ["no-env-filter"] }

[build-dependencies]
# All features enabled
vergen = { version = "8.0.0", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
    "si",
] }
pyo3-build-config = "0.20.0"
